# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  buildVersion: 0.0.1.$(Build.BuildNumber)-alpha.1

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.0.x'
  displayName: 'Install dotnet SDK'
- script: dotnet build --configuration $(buildConfiguration) -p:Version=$(buildVersion) ./GraphLinqQL.MsBuildTask/GraphLinqQL.MsBuildTask.csproj
  displayName: 'Build MSBuild task'
- script: dotnet build --configuration $(buildConfiguration) -p:Version=$(buildVersion)
  displayName: 'Build rest of solution'

- task: CopyFiles@2
  inputs:
    contents: '**\*.nupkg'
    targetFolder: $(Build.ArtifactStagingDirectory)
  displayName: 'Copy NuGet packages to staging directory'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: 'packages'
    publishLocation: 'Container'
  displayName: 'Upload NuGet packages to pipeline artifacts'
